/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
  aws_project_region: "us-west-2",
  aws_appsync_graphqlEndpoint:
    "https://3pav4qtswrfitomkrserln4kma.appsync-api.us-west-2.amazonaws.com/graphql",
  aws_appsync_region: "us-west-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-hhh3kfwgkjen3fefclilhmlcyy"
};

export default awsconfig;
